basic:
  checkpoint: null # set to -1 to load last saved model
  headless: true # set to true to run without rendering
  max_iterations: 60000 # set the maximum number of learning iterations to train for
  sim_device: "cuda:0" # device for physics simulation
  rl_device: "cuda:0" # device for the RL algorithm
  seed: 42 # seed - set to -1 to choose random seed
  description: ""

env:
  num_envs: 10
  num_observations: 36
  num_privileged_obs: 14 # if not None a priviledge_obs_buf will be returned by step() (critic obs for assymetric training). None is returned otherwise 
  num_actions: 10
  env_spacing: 1.  # not used with heightfields/trimeshes 
  allow_side_roll: false # allow the robot to roll sideways

runner:
  num_stack: 50
  horizon_length: 24
  mini_epochs: 20
  save_interval: 100
  use_wandb: true

viewer:
  pos: [3., -3., 2.]  # [m]
  lookat: [0., 0., 0.]  # [m]
  record_video: true  # only in play
  record_interval: 1.  # [s]
  record_env_idx: 0

algorithm:
  num_embedding: 64
  learning_rate: 1.e-5
  gamma: 0.995
  lam: 0.95
  bound_coef: 1.0
  denoising_coef: 1.0
  embedding_norm_coef: 1.0
  entropy_coef: -0.01
  symmetric_coef: 10.
  desired_kl: 0.01

sim:
  dt: 0.004
  substeps: 2
  up_axis: "z"
  gravity: [0.0, 0.0, -9.81]
  physics_engine: "physx" # "physx" or "flex"
  physx:
    num_threads: 4 # Number of worker threads per scene used by PhysX - for CPU PhysX only.
    solver_type: 1 # 0: pgs, 1: tgs
    num_position_iterations: 4
    num_velocity_iterations: 1
    contact_offset: 0.02
    rest_offset: 0.0
    bounce_threshold_velocity: 0.2
    max_depenetration_velocity: 100.0
    default_buffer_size_multiplier: 5.0
    max_gpu_contact_pairs: 8388608 # 8*1024*1024
    num_subscenes: 4 # Splits the simulation into N physics scenes and runs each one in a separate thread
    contact_collection: 1 # 0: CC_NEVER (don't collect contact info), 1: CC_LAST_SUBSTEP (collect only contacts on last substep), 2: CC_ALL_SUBSTEPS (broken - do not use!)

asset:
  file: "/home/casbot/ZHZ_ws/HiFAR/resources/CAS02/urdf/CB02_URDF(ECS-WK)-1.urdf"
  name: "CAS02"
  base_name: "base_link"
  foot_names: ["left_leg_ankle_roll_link", "right_leg_ankle_roll_link"]
  disable_gravity: false
  collapse_fixed_joints: true # bug: if collapse_fixed_joints = false, foot doesn't collide with ground
  fix_base_link: false # fixe the base of the robot
  self_collisions: 0 # 1 to disable, 0 to enable...bitwise filter
  replace_cylinder_with_capsule: false # replace collision cylinders with capsules, leads to faster/more stable simulation
  flip_visual_attachments: false # Some .obj meshes must be flipped from y-up to z-up
  density: 0.001
  angular_damping: 0.
  linear_damping: 0.
  max_angular_velocity: 1000.
  max_linear_velocity: 1000.
  armature: 0.
  thickness: 0.01
  toe_pos: [0.1765, 0.0, -0.05] # x,y,z [m]
  heel_pos: [-0.1165, 0.0, -0.05] # x,y,z [m]

init_state:
  pos: [0.0, 0.0, 1.3] # x,y,z [m]
  rot: [0.0, 0.0, 0.0, 1.0] # x,y,z,w [quat]
  lin_vel: [0.0, 0.0, 0.0]  # x,y,z [m/s]
  ang_vel: [0.0, 0.0, 0.0]  # x,y,z [rad/s]
  default_joint_angles: {"pelvic_pitch_joint": -0.2, 
                         "knee": 0.4, 
                         "ankle_pitch": -0.25,
                         "shoulder_pitch": 0.2, 
                         "left_shoulder_roll": 0.09, 
                         "right_shoulder_roll": -0.09, 
                         "elbow": -0.5, 
                         "default": 0.} # target angles when action = 0.0
  reference_num: 4
  reference_joint_angles_1: {"pelvic_pitch_joint": -1.46,
                             "knee": 1.64, 
                             "ankle_pitch": -0.41, 
                             "shoulder_pitch": 0.2, 
                             "left_shoulder_roll": 0.09, 
                             "right_shoulder_roll": -0.09, 
                             "elbow": -0.5, 
                             "default": 0.}
  reference_joint_angles_2: {"pelvic_pitch_joint": -1.62, 
                             "knee": 1.24, 
                             "ankle_pitch": -0.49, 
                             "shoulder_pitch": -0.8, 
                             "left_shoulder_roll": 0.09, 
                             "right_shoulder_roll": -0.09, 
                             "elbow": -2., 
                             "default": 0.}
  reference_joint_angles_3: {"pelvic_pitch_joint": -1.58, 
                             "knee": 1.27, 
                             "ankle_pitch": -0.5, 
                             "shoulder_pitch": -1.63, 
                             "left_shoulder_roll": 0.09, 
                             "right_shoulder_roll": -0.09, 
                             "elbow": -0.7, 
                             "default": 0.}
  reference_joint_angles_4: {"pelvic_pitch_joint": 1.3, 
                             "knee": 0.93, 
                             "ankle_pitch": -0.7, 
                             "shoulder_pitch": 0.2, 
                             "left_shoulder_roll": 0.09, 
                             "right_shoulder_roll": -0.09, 
                             "elbow": -0.5, 
                             "default": 0.}
  pos_num: 10
  dof_pos_mapping:
    1: null
    2: null
    3: null
    4: 0
    5: 0
    6: 1
    7: 2
    8: null
    9: 3
    0: null
  pos_height_mapping:
    1:
      null
    2:
      null
    3:
      null
    4:
      height: 0.8
      pitch: 0.24
    5:
      height: 0.8
      pitch: 0.24
    6:
      height: 0.6
      pitch: 1.27
      roll: -3.14159
    7:
      height: 0.7
      pitch: 1.47
      roll: -3.14159
    8:
      height: 0.45
      pitch: 1.5708
    9:
      height: 0.9
      pitch: -1.5708
    0:
      height: 0.45
      pitch: -1.5708

control:
  drive_mode: 1 # see GymDofDriveModeFlags (0 is none, 1 is pos tgt, 2 is vel tgt, 3 effort)
  stiffness: {"waist": 0., "pelvic": 0., "knee": 0., "ankle": 0., "shoulder": 0., "elbow": 0.} # [N*m/rad]
  damping: {"waist": 0., "pelvic": 0., "knee": 0., "ankle": 0., "shoulder": 0., "elbow": 0.} # [N*m*s/rad]
  action_scale: 1.
  decimation: 5
  effective_ids: [0, 3, 4, 6, 9, 10, 13, 16, 17, 20]

terrain:
  type: "plane" # "plane" or "trimesh"
  static_friction: 1.0  # [-]
  dynamic_friction: 1.0  # [-]
  restitution: 0.        # [-]
  # trimesh only:
  terrain_length: 10.
  terrain_width: 10.
  border_size: 5.
  num_terrains: 8
  terrain_proportions: [0.0, 0.0, 0.5, 0.5] # terrain types: [plane, slope, random, discrete]
  slope: 0.1
  random_height: 0.1
  discrete_height: 0.02
  horizontal_scale: 0.1
  vertical_scale: 0.005
  slope_threshold: 2.0

normalization:
  gravity: 1.0
  lin_vel: 1.0
  ang_vel: 1.0
  dof_pos: 1.0
  dof_vel: 0.1
  filter_weight: 0.1
  push_force: 0.1
  push_torque: 0.5
  clip_actions: 5.

noise:
  gravity:
    range: [0., 0.01]
    operation: "additive"
    distribution: "gaussian"
  lin_vel:
    range: [0., 0.05]
    operation: "additive"
    distribution: "gaussian"
  ang_vel:
    range: [0., 0.1]
    operation: "additive"
    distribution: "gaussian"
  dof_pos:
    range: [0., 0.01]
    operation: "additive"
    distribution: "gaussian"
  dof_vel:
    range: [0., 0.1]
    operation: "additive"
    distribution: "gaussian"
  height:
    range: [0., 0.02]
    operation: "additive"
    distribution: "gaussian"

randomization:
  init_dof_pos:
    range: [0., 0.05]
    operation: "additive"
    distribution: "gaussian"
  init_base_pos_xy:
    range: [-1., 1.]
    operation: "additive"
    distribution: "uniform"
  init_base_lin_vel_xy:
    range: [0., 0.1]
    operation: "additive"
    distribution: "gaussian"

  kick_interval_s: 2.
  kick_lin_vel:
    range: [0., 0.1]
    operation: "additive"
    distribution: "gaussian"
  kick_ang_vel:
    range: [0., 0.02]
    operation: "additive"
    distribution: "gaussian"

  push_interval_s: 5.
  push_duration_s: 1.
  push_force:
    range: [0., 3.]
    operation: "additive"
    distribution: "gaussian"
  push_torque:
    range: [0., 1.]
    operation: "additive"
    distribution: "gaussian"

  stiffness:
    range: [0.95, 1.05]
    operation: "scaling"
    distribution: "uniform"
  damping:
    range: [0.95, 1.05]
    operation: "scaling"
    distribution: "uniform"

  friction:
    range: [0.1, 2.0]
    operation: "additive"
    distribution: "uniform"
  compliance:
    range: [0.5, 1.5]
    operation: "additive"
    distribution: "uniform"
  restitution:
    range: [0.1, 0.9]
    operation: "additive"
    distribution: "uniform"

  base_com:
    range: [-0.1, 0.1]
    operation: "additive"
    distribution: "uniform"
  base_mass:
    range: [0.8, 1.2]
    operation: "scaling"
    distribution: "uniform"
  other_com:
    range: [-0.005, 0.005]
    operation: "additive"
    distribution: "uniform"
  other_mass:
    range: [0.98, 1.02]
    operation: "scaling"
    distribution: "uniform"

rewards:
  scales:
    survival: 4.0
    base_height: 8.0
    stand: 2.0
    orientation: -1.
    torques: -1.e-5
    torque_tiredness: -1.e-2
    power: -2.e-3
    lin_vel_z: -0.
    ang_vel_xy: -0.
    dof_pos_ref: -3.e-1
    dof_vel: -1.e-3
    dof_acc: -1.e-6
    root_acc: -1.e-4
    action_rate: -1.e-3
    dof_pos_limits: -1.
    dof_vel_limits: -0.
    torque_limits: -0.
    collision: -1.
    waist_pos: -0.
    feet_slip: -0.
    feet_vel_z: -0.
    feet_yaw_diff: -0.
    feet_yaw_mean: -0.
    feet_roll: -0.
    feet_distance: -0.
    feet_contact_number: -0.
  episode_length_s: 10.
  terminate_height: 0.2
  terminate_vel: 1000 #80.
  terminate_contacts_on: []
  penalize_contacts_on: []
  only_positive_rewards: true # if true negative total rewards are clipped at zero (avoids early termination problems)
  tracking_sigma: 0.25 # tracking reward = exp(-error^2/sigma)
  base_height_target: 0.92
  base_height_sigma: 0.1
  soft_dof_pos_limit: 1. # percentage of urdf limits, values above this limit are penalized
  soft_dof_vel_limit: 1.
  soft_torque_limit: 1.
  feet_distance_ref: 0.2
